### ISSUE TITLE
Compare panics when an argument is nil

### ISSUE THREAD

**Issue by rosenhouse** [pivotal-cf-experimental/gomegamatchers#1]
In `internal/deepequal/compare_test.go`, add this test:

```go
	Context("when one value is nil", func() {
		It("does not panic", func() {
			expected := map[string]interface{}{}
			var actual interface{}
			deepequal.Compare(expected, actual)
		})
	})
```

It panics :-)

Cheers,
@rosenhouse & @sykesm

**Comment by zankich** [comment]
@rosenhouse fixed in https://github.com/pivotal-cf-experimental/gomegamatchers/commit/79ff89d6cd69e4177c6c766a26fbeaa776f4dae6
