### ISSUE TITLE
license of yaml v2

### ISSUE THREAD

**Issue by luisapace** [pivotal-cf-experimental/gomegamatchers#5]
Hi, in Confab code and Confab-windows code, at  confab/vendor/github.com/pivotal-cf-experimental/gomegamatchers/vendor/gopkg.in/yaml.v2 i's specified LGPL V3 as licence, while in https://github.com/go-yaml/yaml, the license file at https://github.com/go-yaml/yaml/blob/v2/LICENSE indicates Apache V2 as license. 
Is there an error? could you please confirm the licence of yaml.v2 included in Confab and Confab windows: LGPLV3 or Apache v2?

Thanks

**Comment by evanfarrar** [comment]
This has been resolved by upgrading to the latest Apache v2 version of the code.
